version: "3"

services:
  gerador-dados:
    build: ./gerador_dados
    volumes:
      - ./data:/data

  analise-r:
    build: ./analise_r
    volumes:
      - ./data:/data
    depends_on:
      - gerador-dados

  jenkins:
    build: ./jenkins_custom
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: unless-stopped

volumes:
  jenkins_home:
