services:
  gerador-dados:
    build: ./gerador_dados
    volumes:
      - "./data:/data"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin_ist
      POSTGRES_PASSWORD: istunifeob
      POSTGRES_DB: ist_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  analise-dados:
    build: ./analise_r
    volumes:
      - "./data:/data"
    depends_on:
      - gerador-dados
      - postgres

  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - postgres
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_LOG_LEVEL: debug

volumes:
  pgdata:
  grafana-data:
