Essa análise mostra um histograma inicial da base de dados gerados em Python
```{r}
#Inserção dos Dados
dados_IST = read.csv("dados_ist.csv", sep= ',', na.string = "", stringsAsFactors = T, header= T)
```

```{r}
#Exploração dos Dados
head(dados_IST)
summary(dados_IST)
str(dados_IST)
boxplot(dados_IST)

#Analise dos Dados de Nome (Categórico)
summary(dados_IST$nome)
countsNome = table(dados_IST$nome)
countsNome
barplot(countsNome, main="Nome do Paciente", xlab="Nome")
boxplot(dados_IST$nome)

#Analise dos Dados de Idade (Numérico)
summary(dados_IST$idade)
boxplot(dados_IST$idade)
hist(dados_IST$idade)
countsIdade = table(dados_IST$idade)
barplot(countsIdade, main="Idade dos Pacientes", xlab="Idade")

#Analise dos Dados de Genero (Categórico)
summary(dados_IST$genero)
countsGenero = table(dados_IST$genero)
countsGenero
barplot(countsGenero, main="Genero do Paciente", xlab="Genero")
boxplot(dados_IST$genero)

#Analise dos Dados de IST (Numérico)
summary(dados_IST$ist)
boxplot(dados_IST$ist)
hist(dados_IST$ist)
countsIST = table(dados_IST$ist)
barplot(countsIST, main="IST", xlab="IST")

#Analise dos Dados de Doença (Categórico)
summary(dados_IST$doenca)
countsDoenca = table(dados_IST$doenca)
countsDoenca
barplot(countsDoenca, main="Doenças", xlab="Nome da Doença")
boxplot(dados_IST$doenca)

#Analise dos Dados de Localidade (Categórico)
summary(dados_IST$localidade)
countsLocal = table(dados_IST$localidade)
countsLocal
barplot(countsLocal, main="Localidade", xlab="Nome da Cidade")
boxplot(dados_IST$localidade)

#Analise dos Dados de Renda Média (Numérico)
summary(dados_IST$renda_media)
boxplot(dados_IST$renda_media)
hist(dados_IST$renda_media)
countsRenda = table(dados_IST$renda_media)
barplot(countsRenda, main="Renda Média do Paciente", xlab="Valor de Renda")

#Analise dos Dados de Data do Teste (Categórico)
summary(dados_IST$data_teste)
countsData = table(dados_IST$data_teste)
countsData
barplot(countsData, main="Data de Realização do Teste", xlab="Data")
boxplot(dados_IST$data_teste)
```

Verificando Valores Nulos
```{r}
dados_IST[!complete.cases(dados_IST),]

#Conclusão: Não há valores nulos na base IST
```

