- name: Configurar VM de Geração de Dados
  hosts: data_generator
  become: true
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes

    - name: Instalar pacotes essenciais
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Instalar venv
      command: python3 -m venv /home/vagrant/venv

    - name: Instalar dependências no ambiente virtual
      command: /home/vagrant/venv/bin/pip install pandas numpy faker

    - name: Instalar bibliotecas Python
      pip:
        name:
          - pandas
          - numpy
          - faker

    - name: Copiar script de geração de dados
      copy:
        src: ../scripts/generate_data.sh
        dest: /home/vagrant/generate_data.sh
        mode: "0755"

    - name: Executar script de geração de dados
      command: bash /home/vagrant/generate_data.sh
